version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2022-04-09T15-09-52Z
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: user12345
      MINIO_SECRET_KEY: key12345
    command: server /data --console-address ":9001"